// Endpoint paths and schemas are based on the forum's public developer documentation.
// All example IDs, names, credentials, and returned values below are illustrative.
const apiAuth=[['token_type','string','필수','본문','Discord OAuth2 토큰 유형. 예: Bearer'],['access_token','string','필수','본문','Discord OAuth2 액세스 토큰']];
const apiPaging=(min)=>[['page','integer','필수','쿼리','페이지 번호. 1 이상의 정수'],['count','integer','필수','쿼리',`페이지 크기. ${min}–1000 사이 정수`]];
const apiExampleUser={user_id:101,nickname:'ExamplePlayer',is_korean:true};
const apiLevelExample={level_id:123,level_name:'Example Level',level_rank:1,pointercrate_rank:null,is_legacy:false,require_percent:70,publisher:apiExampleUser,creators:[apiExampleUser],verifier:apiExampleUser,video_url:'https://www.youtube.com/watch?v=VIDEO_ID',category:'XL,2023',rate_point:24,rate_users:6,score:1000};
const apiRequestExample={request_id:21282,type:0,data:{user_id:101,nickname:'ExamplePlayer',level_id:123,percent:100,device:'Mobile',fps:120,bypass:false,cbf:false,video:'https://www.youtube.com/watch?v=VIDEO_ID',raw_video:'https://example.com/raw-video',description:'기록 제출 예시'},status:'대기중',approve_date:null,request_date:1788825600000};
const apiTokenBody={token_type:'Bearer',access_token:'<DISCORD_ACCESS_TOKEN>'};
const apiEndpoints=[
{id:'levels',group:'데몬리스트',method:'GET',path:'/demonlist/levels',title:'레벨 목록 조회',desc:'난이도 순서로 정렬된 레벨 목록을 페이지 단위로 가져옵니다.',params:apiPaging(1),query:'?page=1&count=20',response:[apiLevelExample],returns:'data는 레벨 객체의 배열입니다. 순위, 제작·검증 유저, 인정 진행률과 100% 클리어 점수를 포함합니다.'},
{id:'level-detail',group:'데몬리스트',method:'GET',path:'/demonlist/levels/{value}',title:'레벨 상세 조회',desc:'레벨 ID, 순위 또는 이름으로 메타데이터와 클리어 기록·평가를 가져옵니다.',params:[['value','string | integer','필수','경로','찾을 레벨의 ID·순위·이름'],['find_by','string','필수*','쿼리','id / rank / name. 문서상 기본값: id']],examplePath:'/demonlist/levels/123',query:'?find_by=id',note:'기존 문서에서 find_by는 필수 항목과 기본값이 함께 표기되어 있어 예시에서는 명시적으로 전달합니다. name은 대소문자를 구분합니다.',response:{...apiLevelExample,ingame_level_id:86407629,ingame_objects:220116,highest_rank:1,warn_message:'',records:[{user:apiExampleUser,percent:100,video_url:'https://www.youtube.com/watch?v=VIDEO_ID',device_type:'Mobile',device_fps:120,is_fps_bypass:false,is_cbf:false,score:1000}],comments:[{context:'평가 내용 예시',upload_date:1788825600,user:apiExampleUser,rates:4}]},returns:'data는 레벨 객체입니다. 아래 응답은 주요 필드만 담은 축약 예시이며, 캐싱되지 않은 인게임 정보는 null일 수 있습니다.'},
{id:'leaderboard',group:'데몬리스트',method:'GET',path:'/demonlist/leaderboard',title:'유저 포인트 리더보드',desc:'한국 유저를 데몬리스트 포인트 순으로 조회합니다.',params:apiPaging(10),query:'?page=1&count=20',response:[{rank:1,user_id:101,nickname:'ExamplePlayer',point:125000,achievements:'',trophy:'top1'}],returns:'data는 순위가 정렬된 유저 배열입니다. achievements는 쉼표로 구분된 메달 값이며 trophy는 트로피 등급입니다.'},
{id:'comments',group:'데몬리스트',method:'POST',path:'/demonlist/levels/{level_id}/comments',title:'레벨 평가 등록',desc:'Discord에 연동된 유저의 이름으로 레벨 평가를 등록합니다.',auth:true,limit:'10분당 20회',params:[['level_id','integer','필수','경로','평가할 레벨의 ID'],...apiAuth,['rates','integer','필수','본문','평점 값. 허용 범위는 기존 문서에 미기재'],['context','string','필수','본문','평가 내용'],['is_hide','boolean','선택','본문','기존 평가의 숨김 여부']],examplePath:'/demonlist/levels/123/comments',body:{...apiTokenBody,rates:4,context:'평가 내용 예시',is_hide:false},response:567,note:'레벨을 클리어한 유저만 평가할 수 있으며, 유저별 평가는 하나만 등록할 수 있습니다.',returns:'data는 등록된 평가 ID를 나타내는 정수입니다.'},
{id:'stats',group:'스탯랭킹',method:'GET',path:'/statrank/{stat}',title:'스탯랭킹 조회',desc:'선택한 게임 스탯의 순위와 2주 전 수치를 조회합니다.',params:[['stat','string','필수','경로','stars / moons / demons / diamonds / coins / creator_points (cp) / extreme_demons (ed)']],examplePath:'/statrank/stars',response:[{rank:1,account_nickname:'ExamplePlayer',stat_value:235821,ingame_rank:12,prev_stat_value:232294,prev_ingame_rank:13,account_id:12345,player_id:67890}],returns:'data는 유저 배열입니다. prev_stat_value와 prev_ingame_rank는 이전 데이터가 없으면 null입니다. 증감은 현재 값에서 이전 값을 빼서 계산합니다.'},
{id:'user',group:'유저 · 계정',method:'GET',path:'/users/{find_by}/{value}',title:'ID·닉네임으로 유저 조회',desc:'포럼 유저를 조회하고 필요한 데이터 묶음만 선택해 가져옵니다.',params:[['find_by','string','필수','경로','id 또는 name'],['value','string | integer','필수','경로','유저 ID 또는 닉네임. 닉네임은 대소문자 미구분'],['config','string','선택','쿼리','demonlist / demonlist.records / demonlist.comments. 여러 값은 쉼표로 구분']],examplePath:'/users/id/101',query:'?config=demonlist',response:{...apiExampleUser,achievements:'',demonlist:{point:125000,rank:1,trophy:'top1'}},returns:'data는 유저 객체입니다. config를 생략하면 기본 정보만 반환하며, 지정하면 포인트·기록·평가 정보를 확장합니다.'},
{id:'link',group:'유저 · 계정',method:'POST',path:'/users/link',title:'Discord 계정 연동',desc:'Discord 계정을 기존 포럼 유저와 연결합니다.',auth:true,limit:'1시간당 20회',params:[['user_id','integer','필수','본문','연동할 포럼 유저 ID'],...apiAuth],body:{user_id:101,...apiTokenBody},response:'연동 완료 메시지 예시',note:'YouTube 영상이 연결된 클리어 기록이 필요합니다. Discord Connections의 YouTube 채널과 기록 영상의 채널이 일치해야 합니다.',returns:'data는 완료 메시지 문자열입니다. 아래 문구는 설명용 예시입니다.'},
{id:'unlink',group:'유저 · 계정',method:'POST',path:'/users/unlink',title:'Discord 연동 해제',desc:'Discord 계정과 포럼 유저 사이의 연동을 해제합니다.',auth:true,limit:'1시간당 5회',params:apiAuth,body:apiTokenBody,response:'연동 해제 메시지 예시',returns:'data는 완료 메시지 문자열입니다. 아래 문구는 설명용 예시입니다.'},
{id:'link-code',group:'유저 · 계정',method:'POST',path:'/users/link_gd/generate',title:'게임 계정 연동코드 발급',desc:'Geometry Dash 계정의 소유 확인에 사용할 코드와 UUID를 발급합니다.',limit:'1시간당 20회',params:[],note:'기존 문서에 필수 파라미터가 명시되어 있지 않습니다. 발급된 code는 인게임 GMDKoreaForum 계정으로 보내는 메시지의 제목에 사용합니다.',body:{},response:{code:'EXAMPLE-CODE',uuid:'00000000-0000-4000-8000-000000000000'},returns:'data.code는 인게임 메시지용 코드, data.uuid는 이후 요청을 식별하는 값입니다.'},
{id:'request-create',group:'리퀘스트',method:'POST',path:'/requests',title:'리퀘스트 생성',desc:'기록 등재, 스탯랭킹 등재 또는 닉네임 변경을 신청합니다.',auth:true,limit:'1시간당 20회',params:[['request_type','integer','필수','본문','1: 데몬리스트 기록 / 2: 스탯랭킹 등재 / 4: 닉네임 변경'],...apiAuth,['user_id','integer | null','조건부','본문','기록 신청 시 유저 ID. 신규 유저는 null'],['nickname','string','조건부','본문','신규 유저 또는 닉네임 변경 시 사용. 3–32자'],['level_id','integer','조건부','본문','기록 신청 대상 레벨 ID'],['percent','integer','조건부','본문','기록 신청의 달성 진행률'],['device','string','조건부','본문','기록 신청: PC / iPad / Mobile'],['fps','integer','조건부','본문','기록 신청의 플레이 FPS'],['bypass','boolean','조건부','본문','FPS Bypass 사용 여부'],['cbf','boolean','조건부','본문','Click Between Frames 사용 여부'],['video','URL','조건부','본문','클리어 영상 주소'],['raw_video','URL','조건부','본문','무편집 원본 영상 주소'],['description','string','조건부','본문','전달할 설명. 120자 미만'],['link_uuid','string','조건부','본문','스탯랭킹 신청 시 계정 확인 UUID']],body:{request_type:1,...apiTokenBody,user_id:101,nickname:'ExamplePlayer',level_id:123,percent:100,device:'Mobile',fps:120,bypass:false,cbf:false,video:'https://www.youtube.com/watch?v=VIDEO_ID',raw_video:'https://example.com/raw-video',description:'기록 제출 예시'},response:'리퀘스트 등록 메시지 예시',note:'조건부 항목은 신청 종류에 따라 달라집니다. 생성의 request_type(1·2·4)과 조회 응답의 type(0·1·3)은 서로 다른 값 체계입니다.',returns:'data는 등록 결과를 안내하는 문자열입니다. 아래 문구는 설명용 예시입니다.'},
{id:'request-account',group:'리퀘스트',method:'GET',path:'/requests/account',title:'내 리퀘스트 목록',desc:'인증한 Discord 계정이 신청한 최근 리퀘스트를 최대 20건 조회합니다.',auth:true,limit:'1시간당 20회',params:[['token-type','string','필수','헤더','Discord OAuth2 토큰 유형. 예: Bearer'],['access-token','string','필수','헤더','Discord OAuth2 액세스 토큰']],headers:{'token-type':'Bearer','access-token':'<DISCORD_ACCESS_TOKEN>'},response:[apiRequestExample],returns:'data는 리퀘스트 배열입니다. 상태는 대기중·거절됨·승인됨이며, 처리 전 approve_date는 null입니다.'},
{id:'request-detail',group:'리퀘스트',method:'GET',path:'/requests/{request_id}',title:'리퀘스트 단건 조회',desc:'리퀘스트 ID로 제출 내용과 처리 상태를 조회합니다.',params:[['request_id','integer','필수','경로','조회할 리퀘스트 ID']],examplePath:'/requests/21282',response:apiRequestExample,returns:'data는 리퀘스트 객체입니다. type은 0: 기록 등재, 1: 스탯랭킹 등재, 3: 닉네임 변경을 뜻합니다.'}
];
const apiCodeStore=new Map();let apiCodeId=0;let apiObserver;
function apiHighlight(source){
  const pattern=/("(?:\\.|[^"\\])*"|'[^'\n]*'|\b(?:true|false|null)\b|\b\d+(?:\.\d+)?\b|\b(?:GET|POST)\b|^\w[\w-]*(?=:))/gm;
  let out='',last=0;for(const match of source.matchAll(pattern)){const s=match[0],index=match.index;out+=esc(source.slice(last,index));const tail=source.slice(index+s.length);let cls=s[0]==='"'?( /^\s*:/.test(tail)?'token-key':'token-string'):s[0]==="'"?'token-string':/^(GET|POST)$/.test(s)?'token-method':/^(true|false|null)$/.test(s)?'token-value':/^\d/.test(s)?'token-number':'token-key';out+=`<span class="${cls}">${esc(s)}</span>`;last=index+s.length}return out+esc(source.slice(last));
}
function apiCode(source,title,language='json'){let id='api-code-'+(++apiCodeId);apiCodeStore.set(id,source);return `<div class="api-code"><div class="api-code-head"><span>${title}<b>${language.toUpperCase()}</b></span><button data-copy-code="${id}" aria-label="${title} 복사">${icon('copy')}복사</button></div><pre tabindex="0" aria-label="${title}"><code>${apiHighlight(source)}</code></pre></div>`}
function apiParamTable(params){return `<div class="api-table"><table><thead><tr><th scope="col">파라미터</th><th scope="col">타입</th><th scope="col">필수 여부</th><th scope="col">위치</th><th scope="col">설명</th></tr></thead><tbody>${params.length?params.map(([n,t,req,where,d])=>`<tr><td><code>${esc(n)}</code></td><td><code class="type-code">${esc(t)}</code></td><td><span class="param-required ${req.startsWith('필수')?'required':''}">${req}</span></td><td class="muted">${where}</td><td>${esc(d)}</td></tr>`).join(''):'<tr><td colspan="5" class="muted">기존 문서에 별도 입력 파라미터가 명시되어 있지 않습니다.</td></tr>'}</tbody></table></div>`}
function apiRequestCode(e){return `${e.method} ${e.examplePath||e.path}${e.query||''}\nAccept: application/json${e.headers?'\n'+Object.entries(e.headers).map(([k,v])=>`${k}: ${v}`).join('\n'):''}${e.method==='POST'?'\nContent-Type: application/json\n\n'+JSON.stringify(e.body||{},null,2):''}`}
function apiEndpoint(e){return `<section class="api-endpoint" id="${e.id}" aria-labelledby="${e.id}-title"><h2 id="${e.id}-title">${e.title}<a href="#${e.id}" class="anchor-link" aria-label="${e.title} 바로가기">#</a></h2><div class="api-signature"><span class="method method-${e.method.toLowerCase()}">${e.method}</span><code>${esc(e.path)}</code></div><p class="api-prose">${e.desc}</p><div class="endpoint-meta"><span>${e.auth?'Discord OAuth2 필요':'별도 인증 명시 없음'}</span><span>${e.limit||'30분당 1,000회'}</span></div>${e.note?`<div class="api-note"><p>${e.note}</p></div>`:''}<h3>파라미터</h3>${apiParamTable(e.params)}<h3>요청과 응답</h3>${apiCode(apiRequestCode(e),'요청 예시','http')}<p class="api-prose response-description">${e.returns}</p>${apiCode(JSON.stringify({status:'success',data:e.response},null,2),'응답 예시')}</section>`}
function api(){
apiObserver?.disconnect();apiCodeStore.clear();apiCodeId=0;
const groups=['데몬리스트','스탯랭킹','유저 · 계정','리퀘스트'];
main.innerHTML=`<div class="api-shell"><aside class="api-sidebar" aria-label="API 문서 목차"><div class="api-sidebar-title">API 문서</div><nav class="api-toc"><div class="api-toc-label">시작하기</div><a href="#introduction" class="active" data-doc-anchor>소개</a><a href="#structure" data-doc-anchor>공통 응답</a><a href="#rate-limit" data-doc-anchor>호출 제한과 인증</a>${groups.map(g=>`<div class="api-toc-label">${g}</div>${apiEndpoints.filter(e=>e.group===g).map(e=>`<a href="#${e.id}" data-doc-anchor><span class="method-mini ${e.method.toLowerCase()}">${e.method}</span>${e.title}</a>`).join('')}`).join('')}</nav><a class="api-discord" href="https://discord.gg/nnsShzg" target="_blank" rel="noopener noreferrer">Discord 문의 ${icon('external')}</a></aside>
<div class="api-document"><div class="api-mobile-toc"><label for="api-jump">문서 목차</label><select id="api-jump"><option value="introduction">소개</option><option value="structure">공통 응답</option><option value="rate-limit">호출 제한과 인증</option>${apiEndpoints.map(e=>`<option value="${e.id}">${e.method} · ${e.title}</option>`).join('')}</select></div>
<section id="introduction" class="api-introduction"><div class="api-doc-path">개발자 문서 / REST API</div><h1>API 문서</h1><p class="api-prose">한국포럼의 데몬리스트, 유저, 스탯 데이터를 조회하고 기록을 제출하는 방법을 안내합니다.</p><div class="api-summary"><span>엔드포인트 <strong>12개</strong></span><span>응답 형식 <strong>JSON</strong></span><span>호출 한도 <strong>1,000회 / 30분</strong></span></div><p class="api-source-note">디자인 목업입니다. <a href="https://gmdkoreaforum.com/api/" target="_blank" rel="noopener noreferrer">기존 공개 문서</a>를 재구성했으며, 요청·응답 값은 설명용 예시입니다. 서버 주소가 원문에 명시되지 않아 요청은 상대 경로로 표시했습니다.</p></section>
<section id="structure" class="api-common"><h2>공통 응답</h2><p class="api-prose">모든 응답은 <code>status</code>와 <code>data</code>로 감싸집니다. 성공 시 <code>data</code>의 타입은 엔드포인트마다 다르며, 실패 시에는 오류 메시지가 반환됩니다.</p><div class="api-response-pair">${apiCode(JSON.stringify({status:'success',data:{user_id:101,nickname:'ExamplePlayer'}},null,2),'성공')}${apiCode(JSON.stringify({status:'error',data:'요청 처리 실패'},null,2),'실패')}</div><div class="api-table"><table><thead><tr><th scope="col">필드</th><th scope="col">타입</th><th scope="col">설명</th></tr></thead><tbody><tr><td><code>status</code></td><td><code>string</code></td><td><code>success</code> 또는 <code>error</code></td></tr><tr><td><code>data</code></td><td><code>object | array | string | integer</code></td><td>응답 데이터 또는 오류 메시지</td></tr></tbody></table></div></section>
<section id="rate-limit" class="api-common"><h2>호출 제한과 인증</h2><p class="api-prose">공통 한도는 30분당 1,000회입니다. 아래 작업에는 별도의 한도가 적용됩니다.</p><div class="api-table"><table><thead><tr><th scope="col">적용 대상</th><th scope="col">호출 한도</th></tr></thead><tbody><tr><td>기본 API</td><td>30분당 1,000회</td></tr><tr><td>레벨 평가 등록</td><td>10분당 20회</td></tr><tr><td>리퀘스트 생성·내 목록, 계정 연동, 연동코드 발급</td><td>1시간당 20회</td></tr><tr><td>Discord 연동 해제</td><td>1시간당 5회</td></tr></tbody></table></div><h3>Discord OAuth2</h3><p class="api-prose">인증이 필요한 POST 요청은 본문의 <code>token_type</code>과 <code>access_token</code>을 사용합니다. 내 리퀘스트 목록 조회는 헤더의 <code>token-type</code>과 <code>access-token</code>을 사용합니다.</p><div class="api-note"><p>예시의 <code>&lt;DISCORD_ACCESS_TOKEN&gt;</code>을 발급받은 토큰으로 대체하세요. 실제 토큰을 공개 코드에 저장하지 마세요. <a href="https://discord.com/developers/docs/topics/oauth2" target="_blank" rel="noopener noreferrer">Discord OAuth2 문서 ↗</a></p></div></section>
<div class="api-endpoints-heading"><h2>엔드포인트</h2><span>GET 7 · POST 5</span></div>${apiEndpoints.map(apiEndpoint).join('')}
<footer class="api-support"><p>API 오류 제보와 사용 문의</p><a href="https://discord.gg/nnsShzg" target="_blank" rel="noopener noreferrer">공식 Discord ${icon('external')}</a></footer>${footer()}</div></div>`;
apiObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;document.querySelectorAll('[data-doc-anchor]').forEach(a=>{const active=a.hash==='#'+entry.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});const select=document.querySelector('#api-jump');if(select)select.value=entry.target.id}}, {rootMargin:'-110px 0px -65% 0px',threshold:0});
main.querySelectorAll('section[id]').forEach(el=>apiObserver.observe(el));
if(location.hash&&document.getElementById(location.hash.slice(1)))requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy-code]');if(!b)return;const value=apiCodeStore.get(b.dataset.copyCode);if(typeof value!=='string')return;try{await navigator.clipboard.writeText(value);b.innerHTML=icon('check')+'복사됨';setTimeout(()=>{if(b.isConnected)b.innerHTML=icon('copy')+'복사'},1800)}catch{toast('자동 복사를 사용할 수 없습니다. 코드블록을 선택해 복사해 주세요.')}});
document.addEventListener('change',e=>{if(e.target.id!=='api-jump')return;const target=document.getElementById(e.target.value);if(target){location.hash=e.target.value;target.scrollIntoView({behavior:'smooth'})}});
