const forumCategories={"top1_level": "순위가 1위였던 레벨", "kf_only": "한국포럼에만 등재된 레벨", "extreme_demon": "익스트림 데몬", "insane_demon": "인세인 데몬", "official_song": "공식맵 노래", "sxl_length": "SXL (4분~)", "xxl_length": "XXL (3분~)", "xl_length": "XL (2분~)", "long_length": "Long (1분~)", "medium_length": "Medium (1분 미만)", "low_objects": "Object 40,000개 이하", "normal_objects": "Object 80,000개 이하", "high_objects": "Object 120,000개 이하", "higher_objects": "Object 200,000개 이하", "heavy_objects": "Object 200,000개 초과", "korean_level": "국내 개인맵/합작", "solo_level": "솔로 레벨", "self_level": "제작참여, 베리파이 유저가 같은 레벨", "collab_level": "~6인 합작", "huge_collab_level": "7-12인 합작", "mega_collab_level": "13인~ 합작", "non_first_victor": "클리어 유저가 없는 레벨", "mobile_victor": "모바일 클리어 유저가 있는 레벨", "year_2026": "2026년 레벨", "year_2025": "2025년 레벨", "year_2024": "2024년 레벨", "year_2023": "2023년 레벨", "year_2022": "2022년 레벨", "year_2021": "2021년 레벨", "year_2020": "2020년 레벨", "year_2019": "2019년 레벨", "year_2018": "2018년 레벨", "year_2017": "2017년 레벨", "year_2016": "2016년 레벨"};
const searchFields={name:'레벨 이름',publisher:'업로더 이름',verifier:'베리파이어 이름',creators:'크리에이터(합작원) 이름',rank:'레벨 순위'};
function defaultLevelFilters(){return {pointercrateRank:false,inverted:false,checkAll:true,categories:[],filter:{name:true,publisher:true,verifier:true,creators:false,rank:true}}}
const levelFilters=defaultLevelFilters();
// Static fixtures only: no current Pointercrate or category data is fetched.
function levelSearchData(level){const creators=levelCreators(level);return {publisher:level.creator,verifier:level.rank===1?'Zoink':'베리파이어 예시',creators,pointercrateRank:level.rank<=150?(level.rank===1?1:level.rank%2===0&&level.rank<150?level.rank+1:level.rank===150?150:level.rank-1):null,categories:['extreme_demon','xl_length',level.rank===1?'heavy_objects':'high_objects',creators.length===1?'solo_level':'mega_collab_level',level.rank===1?'year_2023':'year_2026',...(level.rank===1?['top1_level']:[]),...(level.rank>150?['kf_only']:[])]}}
function matchesLevelFilters(level,query=state.query){
 const data=levelSearchData(level),f=levelFilters;
 if(f.pointercrateRank&&data.pointercrateRank===null)return false;
 if(f.categories.length){const matched=f.checkAll?f.categories.every(c=>data.categories.includes(c)):f.categories.some(c=>data.categories.includes(c));if(matched===f.inverted)return false}
 const q=query.trim().toLowerCase();if(!q)return true;
 const has=value=>String(value).toLowerCase().includes(q);
 return (f.filter.name&&has(level.name))||(f.filter.publisher&&has(data.publisher))||(f.filter.verifier&&has(data.verifier))||(f.filter.creators&&data.creators.some(has))||(f.filter.rank&&Number(q.replace(/^#/,''))===level.rank);
}
function filteredLevels(){const found=levels.filter(l=>matchesLevelFilters(l));return levelFilters.pointercrateRank?found.sort((a,b)=>levelSearchData(a).pointercrateRank-levelSearchData(b).pointercrateRank):found}
function filterActiveCount(){const defaults=defaultLevelFilters();return levelFilters.categories.length+Number(levelFilters.pointercrateRank)+Number(levelFilters.inverted)+Number(!levelFilters.checkAll)+Object.keys(searchFields).filter(k=>levelFilters.filter[k]!==defaults.filter[k]).length}
function refreshFilterCount(){document.getElementById('filter-count').textContent=filterActiveCount()||''}
function resetLevelFilters(){Object.assign(levelFilters,defaultLevelFilters());refreshFilterCount();const form=document.getElementById('advanced-panel');if(form){form.innerHTML=advancedSearchFields()}}
function advancedSearchFields(){const f=levelFilters;return `<fieldset><legend>레벨 정렬</legend><label class="filter-check"><input type="checkbox" name="pointercrateRank" ${f.pointercrateRank?'checked':''}>Pointercrate 순위로 표시</label></fieldset><fieldset><legend>검색 대상</legend><div class="filter-check-grid">${Object.entries(searchFields).map(([key,label])=>`<label class="filter-check"><input type="checkbox" data-search-field="${key}" ${f.filter[key]?'checked':''}>${label}</label>`).join('')}</div></fieldset><fieldset><legend>카테고리 조건</legend><label class="filter-check"><input type="checkbox" name="checkAll" ${f.checkAll?'checked':''}>선택한 카테고리를 모두 포함</label><p class="filter-hint">끄면 선택한 카테고리 중 하나라도 포함한 레벨을 표시합니다.</p><label class="filter-check"><input type="checkbox" name="inverted" ${f.inverted?'checked':''}>조건에 맞는 레벨 제외</label></fieldset><fieldset><legend>카테고리</legend><div class="filter-category-list">${Object.entries(forumCategories).map(([key,label])=>`<label class="filter-check"><input type="checkbox" data-filter-category="${key}" ${f.categories.includes(key)?'checked':''}>${label}</label>`).join('')}</div></fieldset><p class="filter-hint">조건을 바꾸면 바로 적용됩니다. 순위·카테고리는 목업 예시입니다.</p><p id="filter-results" role="status">${filteredLevels().length}개 레벨</p><div class="dialog-actions"><button type="button" class="button-secondary" id="filter-reset">초기화</button><button type="button" class="button-primary" data-close>닫기</button></div>`}
function openAdvancedSearch(){document.getElementById('quick-panel').hidden=true;document.getElementById('quick-toggle').setAttribute('aria-expanded','false');openModal(`${modalHead('레벨 검색 / 정렬 필터')}<form id="advanced-panel" class="advanced-search-form">${advancedSearchFields()}</form>`)}
document.addEventListener('change',e=>{if(!e.target.closest('#advanced-panel'))return;const form=document.getElementById('advanced-panel');['pointercrateRank','checkAll','inverted'].forEach(k=>levelFilters[k]=form.elements.namedItem(k).checked);form.querySelectorAll('[data-search-field]').forEach(el=>levelFilters.filter[el.dataset.searchField]=el.checked);levelFilters.categories=[...form.querySelectorAll('[data-filter-category]:checked')].map(el=>el.dataset.filterCategory);refreshFilterCount();renderList();document.getElementById('filter-results').textContent=filteredLevels().length+'개 레벨'});
document.addEventListener('submit',e=>{if(e.target.id==='advanced-panel')e.preventDefault()});
