// Existing forum assets. Rank and UP thresholds follow src/api/lib.js#getUserTier.
function getUserTier(rank,points){if(!rank)return 'none';if(rank==1)return 'top1';if(rank<=5)return 'gold';if(rank<=15)return 'silver';if(rank<=30)return 'bronze';return [[1800,'green'],[1200,'aqua'],[750,'pink'],[300,'red'],[150,'tealblue'],[75,'purple'],[40,'gray']].find(([minimum])=>points>=minimum)?.[1]||'none'}
const gdTierNames={top1:'1위',gold:'골드',silver:'실버',bronze:'브론즈',green:'그린',aqua:'아쿠아',pink:'핑크',red:'레드',tealblue:'틸블루',purple:'퍼플',gray:'그레이',none:'등급 없음'};
const gdStats={'별':['stars','별'],'문':['moons','문'],'데몬':['demons','데몬'],'크리에이터':['cp','크리에이터 포인트'],'코인':['coins','코인'],'다이아':['diamonds','다이아몬드'],'익스트림':['ed','익스트림 데몬']};
const gdMonthly=['22_07','22_08','22_09','22_10','22_11','22_12','23_01','23_02','23_03','23_04','23_05','23_06'];
const demoAchievements={하늘:['tournament_2022_1st','tournament_2021_2nd','completed_top1_demonlist',...gdMonthly.slice(0,9).map(m=>'event_monthly_demon_'+m)],블루문:['tournament_2021_1st','server_booster','donator_2'],네온:['admin','tournament_2022_3rd'],도토리:['event_monthly_demon_23_05','event_monthly_demon_23_06'],라임:['v4_thanks_for_feedback']};
function gdImage(path,label,classes=''){return `<img class="pix gd-asset ${classes}" src="/gmd-korea-forum-mockup/img/${path}" alt="${esc(label)}" title="${esc(label)}" loading="lazy" decoding="async">`}
function trophyImage(rank,points,classes=''){const tier=getUserTier(rank,points);return gdImage('trophy/'+tier+'_trophy.png',gdTierNames[tier]+' 트로피',classes)}
function statImage(stat,classes=''){const [file,label]=gdStats[stat]||gdStats['별'];return gdImage(file+'.png',label,classes)}
function medalInformation(code){let m;if((m=/^tournament_(2020|2021|2022)_(1st|2nd|3rd|16)$/.exec(code))){const place={'1st':'우승','2nd':'준우승','3rd':'3위','16':'본선 진출'}[m[2]];const name=`제 ${+m[1]-2019}차 한국포럼 토너먼트 ${place}`;return {name,description:name+' 이력입니다.'}}if((m=/^event_monthly_demon_(\d{2}_\d{2})$/.exec(code))&&gdMonthly.includes(m[1])){const [y,month]=m[1].split('_');return {name:`20${y}년 ${month}월 이달의 데몬 달성자`,description:`20${y}년 ${month}월, 이달의 데몬 챌린지에 참가한 이력입니다.`}}const metadata={admin:['한국포럼 운영진','한국포럼 운영진입니다.'],completed_top1_demonlist:['Top 1 Victor','클리어 당시 1위였던 레벨을 클리어한 이력입니다.'],v4_thanks_for_feedback:['4.0 업데이트 피드백 제공자','4.0 업데이트 베타 테스터로 참여한 이력입니다.'],server_booster:['서버 부스터','Discord 서버 부스터 메달입니다.'],donator_1:['후원자 1등급','후원자 등급 메달입니다.'],donator_2:['후원자 2등급','후원자 등급 메달입니다.'],donator_3:['후원자 3등급','후원자 등급 메달입니다.']};const row=metadata[code];return row?{name:row[0],description:row[1]}:null}
function medalImage(code){const m=medalInformation(code);return m?gdImage('medal/'+code+'.png',m.name+' · '+m.description,'medal-asset'):''}
function userAchievements(name){return (demoAchievements[name]||[]).filter(code=>medalInformation(code))}
function compactMedals(name){const all=userAchievements(name);return all.length?`<span class="compact-medals">${all.slice(0,3).map(medalImage).join('')}${all.length>3?`<button class="medal-more" data-profile="${esc(name)}" aria-label="${esc(name)}의 나머지 메달 ${all.length-3}개 보기">+${all.length-3}</button>`:''}</span>`:'<span class="muted">—</span>'}
let demoUserLookup;
function findDemoUser(name){demoUserLookup||=new Map(pointUsers().map((u,index)=>[u.name,{...u,index}]));return demoUserLookup.get(name)||{name,rank:null,points:0,clears:0,hardest:1,index:0}}
function recordTrophy(name){const u=findDemoUser(name);return trophyImage(u.rank,u.points,'record-user-trophy')}
function profileMedals(name){const all=userAchievements(name);if(!all.length)return '<p class="muted profile-empty">보유 메달이 없습니다.</p>';const groups=[['토너먼트',all.filter(c=>c.startsWith('tournament_'))],['이력·활동',all.filter(c=>!c.startsWith('tournament_')&&!c.startsWith('event_'))],['이달의 데몬',all.filter(c=>c.startsWith('event_'))]].filter(([,codes])=>codes.length);return `<div class="profile-medal-groups">${groups.map(([label,codes])=>`<div class="profile-medal-group"><span>${label}</span><div class="profile-medals">${codes.slice(0,3).map(medalImage).join('')}${codes.length>3?`<details class="profile-medal-overflow"><summary aria-label="${label} 메달 ${codes.length-3}개 더 보기">+${codes.length-3}</summary><div>${codes.slice(3).map(medalImage).join('')}</div></details>`:''}</div></div>`).join('')}</div>`}
function openUserProfile(name){document.querySelector('#modal')?.close();changePage('profile/'+encodeURIComponent(name))}
function profileRouteName(){try{return decodeURIComponent(location.hash.slice(1).split('/').slice(1).join('/'))||'하늘'}catch{return '하늘'}}
function demoStatUsers(stat){const mult={별:1,문:.06,데몬:.035,크리에이터:.0008,코인:.013,다이아:1.3,익스트림:.0015}[stat];return Array.from({length:478},(_,i)=>({rank:i+1,name:names[i%16]+(i>=16?String(Math.floor(i/16)+1):''),value:Math.max(1,Math.round((235821-i*423)*mult)),delta:Math.round((3527-i%30*49)*mult)}))}
let profileRecordPage=1,profileRecordName='';
function profilePage(){
 const name=profileRouteName(),u=findDemoUser(name),own=toolState.demoAccount&&name==='하늘';
 if(profileRecordName!==name){profileRecordPage=1;profileRecordName=name}
 document.title=name+' · 프로필 · GMD 한국포럼';
 main.innerHTML=`<div class="profile-page-bar"><button class="record-link" data-page="leaderboard">${icon('chevronLeft')} 유저랭킹</button>${own?'<div class="profile-mobile-actions"><button class="button-secondary" data-account-settings>설정</button><button class="record-link" data-demo-logout>로그아웃</button></div>':''}</div><div class="user-profile-layout"><aside class="user-profile-summary" aria-label="유저 정보"><header class="profile-identity">${trophyImage(u.rank,u.points,'profile-page-trophy')}<h1>${esc(name)}</h1><p>${u.rank?'유저랭킹 '+fmt(u.rank)+'위':'순위 미등재'} · 예시 유저</p></header><dl class="profile-key-numbers"><div><dt>유저포인트</dt><dd>${u.rank?fmt(u.points):'-'} <small>UP</small></dd></div><div><dt>클리어</dt><dd>${u.rank?fmt(u.clears):'-'} <small>개</small></dd></div></dl><section class="profile-section"><h2>보유 메달 <span>${userAchievements(name).length}</span></h2>${profileMedals(name)}</section><section class="profile-section"><h2>인게임 스탯</h2><dl class="profile-stat-grid">${Object.entries(gdStats).map(([stat,[,label]])=>{const row=demoStatUsers(stat).find(r=>r.name===name);return `<div><dt>${statImage(stat)}<span>${label}</span></dt><dd>${row?fmt(row.value):'-'}</dd></div>`}).join('')}</dl></section><p class="tool-sample">스탯랭킹과 같은 예시 데이터를 표시합니다. 미등재 스탯은 -로 표시합니다.</p></aside><section class="profile-records" aria-labelledby="profile-records-title"><header class="profile-records-heading"><h2 id="profile-records-title">클리어 기록 <span>${u.clears}</span></h2><small>예시 기록</small></header><div id="profile-record-list"></div><div id="profile-record-foot" class="table-foot"></div><p class="tool-sample">클리어 목록과 영상은 디자인 확인용 예시입니다.</p></section></div>${footer()}`;
 renderProfileRecords();
}
function renderProfileRecords(){const u=findDemoUser(profileRouteName());const all=u.rank?levels.slice(u.hardest-1,u.hardest-1+u.clears):[];const pages=Math.max(1,Math.ceil(all.length/12));profileRecordPage=Math.max(1,Math.min(profileRecordPage,pages));const start=(profileRecordPage-1)*12;document.querySelector('#profile-record-list').innerHTML=all.slice(start,start+12).map(l=>`<article class="profile-clear-row"><span class="profile-clear-rank">#${l.rank}</span><button class="profile-clear-level" data-home-level="${l.rank}"><strong>${esc(l.name)}</strong><small>제작 ${esc(l.creator)}</small></button><span class="profile-clear-score"><strong>100%</strong><small>${fmt(l.score)} UP</small></span><button class="video-link" data-example-video aria-label="${esc(l.name)} 클리어 영상 예시">${icon('play')}</button></article>`).join('')||'<p class="empty">표시할 클리어 기록이 없습니다.</p>';document.querySelector('#profile-record-foot').innerHTML=`<span>${all.length?start+1:0}–${Math.min(start+12,all.length)} / ${all.length}개</span><div class="tool-pagination"><button data-profile-record-page="${profileRecordPage-1}" ${profileRecordPage===1?'disabled':''} aria-label="클리어 기록 이전 페이지">${icon('chevronLeft')}</button><span>${profileRecordPage} / ${pages}</span><button data-profile-record-page="${profileRecordPage+1}" ${profileRecordPage===pages?'disabled':''} aria-label="클리어 기록 다음 페이지">${icon('chevron')}</button></div>`}


/* 등급 이름 라벨. 색은 gd-assets.css의 --tier-* 토큰(테마별 2벌)에서 온다.
   top1은 gold와 색이 거의 같아져 구분이 안 되므로 CSS에서 단색 배지로 처리한다.
   등급이 없는(none) 유저는 라벨을 달지 않는다. */
const TIER_LABELS={top1:'TOP 1',gold:'GOLD',silver:'SILVER',bronze:'BRONZE',green:'GREEN',aqua:'AQUA',pink:'PINK',red:'RED',tealblue:'TEALBLUE',purple:'PURPLE',gray:'GRAY'};
function tierLabel(rank,points){
  const tier=getUserTier(rank,points), name=TIER_LABELS[tier];
  return name?`<span class="tier-name is-${tier}">${name}</span>`:'';
}
