// Existing forum assets. Rank and UP thresholds follow src/api/lib.js#getUserTier.
function getUserTier(rank,points){if(!rank)return 'none';if(rank==1)return 'top1';if(rank<=5)return 'gold';if(rank<=15)return 'silver';if(rank<=30)return 'bronze';return [[1800,'green'],[1200,'aqua'],[750,'pink'],[300,'red'],[150,'tealblue'],[75,'purple'],[40,'gray']].find(([minimum])=>points>=minimum)?.[1]||'none'}
const gdTierNames={top1:'1위',gold:'골드',silver:'실버',bronze:'브론즈',green:'그린',aqua:'아쿠아',pink:'핑크',red:'레드',tealblue:'틸블루',purple:'퍼플',gray:'그레이',none:'등급 없음'};
const gdStats={'별':['stars','별'],'문':['moons','문'],'데몬':['demons','데몬'],'크리에이터':['cp','크리에이터 포인트'],'코인':['coins','코인'],'다이아':['diamonds','다이아몬드'],'익스트림':['ed','익스트림 데몬']};
const gdMonthly=['22_07','22_08','22_09','22_10','22_11','22_12','23_01','23_02','23_03','23_04','23_05','23_06'];
const demoAchievements={하늘:['tournament_2022_1st','tournament_2021_2nd','completed_top1_demonlist',...gdMonthly.slice(0,9).map(m=>'event_monthly_demon_'+m)],블루문:['tournament_2021_1st','server_booster','donator_2'],네온:['admin','tournament_2022_3rd'],도토리:['event_monthly_demon_23_05','event_monthly_demon_23_06'],라임:['v4_thanks_for_feedback']};
function gdImage(path,label,classes=''){return `<img class="pix gd-asset ${classes}" src="/gmd-korea-forum-mockup/img/${path}" alt="${esc(label)}" title="${esc(label)}" loading="lazy" decoding="async">`}
function trophyImage(rank,points,classes=''){const tier=getUserTier(rank,points);return gdImage('trophy/'+tier+'_trophy.png',gdTierNames[tier]+' 트로피',classes)}
function statImage(stat,classes=''){const [file,label]=gdStats[stat]||gdStats['별'];return gdImage(file+'.png',label,classes)}
function medalInformation(code){let m;if((m=/^tournament_(2020|2021|2022)_(1st|2nd|3rd|16)$/.exec(code))){const place={'1st':'우승','2nd':'준우승','3rd':'3위','16':'본선 진출'}[m[2]];const name=`제 ${+m[1]-2019}차 한국포럼 토너먼트 ${place}`;return {name,description:name+' 이력입니다.'}}if((m=/^event_monthly_demon_(\d{2}_\d{2})$/.exec(code))&&gdMonthly.includes(m[1])){const [y,month]=m[1].split('_');return {name:`20${y}년 ${month}월 이달의 데몬 달성자`,description:`20${y}년 ${month}월, 이달의 데몬 챌린지에 참가한 이력입니다.`}}const metadata={admin:['한국포럼 운영진','한국포럼 운영진입니다.'],completed_top1_demonlist:['Top 1 Victor','클리어 당시 1위였던 레벨을 클리어한 이력입니다.'],v4_thanks_for_feedback:['4.0 업데이트 피드백 제공자','4.0 업데이트 베타 테스터로 참여한 이력입니다.'],server_booster:['서버 부스터','Discord 서버 부스터 메달입니다.'],donator_1:['후원자 1등급','후원자 등급 메달입니다.'],donator_2:['후원자 2등급','후원자 등급 메달입니다.'],donator_3:['후원자 3등급','후원자 등급 메달입니다.']};const row=metadata[code];return row?{name:row[0],description:row[1]}:null}
function medalImage(code){const m=medalInformation(code);return m?gdImage('medal/'+code+'.png',m.name+' · '+m.description,'medal-asset'):''}
function userAchievements(name){return (demoAchievements[name]||[]).filter(code=>medalInformation(code))}
function compactMedals(name){const all=userAchievements(name);return all.length?`<span class="compact-medals">${all.slice(0,3).map(medalImage).join('')}${all.length>3?`<button class="medal-more" data-profile="${esc(name)}" aria-label="${esc(name)}의 나머지 메달 ${all.length-3}개 보기">+${all.length-3}</button>`:''}</span>`:'<span class="muted">—</span>'}
let demoUserLookup;
function findDemoUser(name){demoUserLookup||=new Map(pointUsers().map((u,index)=>[u.name,{...u,index}]));return demoUserLookup.get(name)||{name,rank:null,points:0,clears:0,hardest:1,index:0}}
function recordTrophy(name){const u=findDemoUser(name);return trophyImage(u.rank,u.points,'record-user-trophy')}
function profileMedals(name){const all=userAchievements(name);if(!all.length)return '<p class="muted profile-empty">보유 메달이 없습니다.</p>';const groups=[['토너먼트',all.filter(c=>c.startsWith('tournament_'))],['이력·활동',all.filter(c=>!c.startsWith('tournament_')&&!c.startsWith('event_'))],['이달의 데몬',all.filter(c=>c.startsWith('event_'))]].filter(([,codes])=>codes.length);return `<div class="profile-medal-groups">${groups.map(([label,codes])=>`<div class="profile-medal-group"><span>${label}</span><div class="profile-medals">${codes.slice(0,3).map(medalImage).join('')}${codes.length>3?`<details class="profile-medal-overflow"><summary aria-label="${label} 메달 ${codes.length-3}개 더 보기">+${codes.length-3}</summary><div>${codes.slice(3).map(medalImage).join('')}</div></details>`:''}</div></div>`).join('')}</div>`}
function openUserProfile(name){const u=findDemoUser(name);const mult={'별':1,'문':.06,'데몬':.035,'크리에이터':.0008,'코인':.013,'다이아':1.3,'익스트림':.0015};openModal(`<div class="dialog-head profile-heading">${trophyImage(u.rank,u.points,'profile-trophy')}<div><h2>${esc(name)}</h2><p>${u.rank?'데몬리스트 '+fmt(u.rank)+'위':'순위 미등재'} · 예시 유저</p></div><button class="icon-btn" data-close aria-label="닫기">${icon('close')}</button></div><div class="profile-point-line"><span>유저포인트 <strong>${u.points.toLocaleString('en-US',{maximumFractionDigits:2})} UP</strong></span><span>클리어 <strong>${u.clears}개</strong></span></div><section class="profile-section"><h3>보유 메달 <span>${userAchievements(name).length}</span></h3>${profileMedals(name)}</section><section class="profile-section"><h3>인게임 스탯</h3><dl class="profile-stat-grid">${Object.entries(gdStats).map(([stat,[,label]])=>`<div><dt>${statImage(stat)}<span>${label}</span></dt><dd>${fmt(Math.max(1,Math.round((235821-u.index*423)*mult[stat])))}</dd></div>`).join('')}</dl></section><p class="tool-sample">트로피는 예시 순위·포인트로 계산하며, 보유 메달과 스탯도 예시입니다.</p><div class="dialog-actions"><button class="button-secondary" data-close>닫기</button></div>`)}
