// Public tool screens use illustrative data. Account operations never call a server.
const toolPageTitles={tools:'데몬리스트 도구',leaderboard:'유저포인트 리더보드',calculator:'유저포인트 계산기',roulette:'데몬리스트 룰렛',account:'Discord 연동',nickname:'닉네임 변경 요청','submission-guide':'기록 등재 필독 사항',guidelines:'기록 가이드라인','my-requests':'내 최근 리퀘스트'};
const toolState={boardQuery:'',boardPage:1,calculator:null,rouletteHistory:[],rouletteResult:null,demoAccount:false,linked:false};
const requestPages=['requests','submission-guide','guidelines','my-requests'];
function requestNav(){return `<nav class="demon-tool-nav request-nav" aria-label="리퀘스트 메뉴">${[['requests','기록 제출'],['submission-guide','등재 필독 사항'],['guidelines','가이드라인'],['my-requests','내 리퀘스트']].map(([p,n])=>`<button data-page="${p}" ${state.page===p?'aria-current="page"':''}>${n}</button>`).join('')}</nav>`}
const toolGroups=[
  {title:'플레이 도구',desc:'순위를 확인하고 다음 도전을 고릅니다.',items:[['leaderboard','유저포인트 리더보드','클리어 기록으로 쌓은 포인트 순위'],['calculator','유저포인트 계산기','진행률·기기 조건에 따른 예상 포인트'],['roulette','데몬리스트 룰렛','순위 범위 안에서 도전할 레벨 추첨']]},
  {title:'계정 관리',desc:'기록과 내 계정을 연결합니다.',items:[['account','Discord 연동','로그인 상태와 포럼 유저 연동'],['nickname','닉네임 변경 요청','기존 기록을 유지한 채 이름 변경 신청']]}
];
function demonToolNav(){return `<nav class="demon-tool-nav" aria-label="데몬리스트 도구 메뉴">${[['demon','레벨'],['leaderboard','유저포인트'],['calculator','계산기'],['roulette','룰렛'],['tools','전체 도구']].map(([p,n])=>`<button data-page="${p}" ${state.page===p?'aria-current="page"':''}>${n}${p==='tools'?'<span>5</span>':''}</button>`).join('')}</nav>`}
function toolHeading(title,desc){return `<div class="tool-heading"><div><h1>${title}</h1><p>${desc}</p></div>${requestPages.includes(state.page)?'<button class="record-link" data-page="requests">리퀘스트 '+icon('chevron')+'</button>':state.page!=='tools'?'<button class="record-link" data-page="tools">전체 도구 '+icon('chevron')+'</button>':''}</div>`}
function toolSample(text='화면에 표시된 유저·순위·기록은 예시입니다.'){return `<p class="tool-sample">디자인 목업 · ${text}</p>`}
function toolsHome(){main.innerHTML=`${toolHeading('데몬리스트 도구','순위 확인, 다음 도전과 계정 관리에 필요한 기능입니다.')}<div class="tool-directory">${toolGroups.map(g=>`<section><header><h2>${g.title}</h2><p>${g.desc}</p></header><div>${g.items.map(([p,n,d])=>`<button class="tool-directory-item" data-page="${p}"><span><strong>${n}</strong><small>${d}</small></span>${icon('chevron')}</button>`).join('')}</div></section>`).join('')}</div><p class="tool-sample">기록 제출과 등재 필독 사항·가이드라인은 <button class="inline-link" data-page="requests">리퀘스트</button>에서 확인하세요.</p>${toolSample()}${footer()}`}
function pointUsers(){return Array.from({length:1677},(_,i)=>({rank:i+1,name:names[i%names.length]+(i>=names.length?String(Math.floor(i/names.length)+1):''),points:Math.max(1,125000-i*73.8),clears:Math.max(1,384-Math.floor(i/5)),hardest:Math.min(940,1+Math.floor(i/6))}))}
function pointLeaderboard(){main.innerHTML=`${toolHeading('유저포인트 리더보드','데몬리스트의 승인 기록으로 쌓은 포인트 순위입니다.')}<div class="tool-table-toolbar"><span>순위 등재 <strong>1,677명</strong><small> · 예시 데이터</small></span><label class="search-box">${icon('search')}<input id="point-search" aria-label="포인트 리더보드 유저 검색" placeholder="닉네임 검색" value="${esc(toolState.boardQuery)}"></label></div><div class="table-container"><table class="point-table"><thead><tr><th scope="col">순위</th><th scope="col" class="tier-column">등급</th><th scope="col">유저</th><th scope="col" class="num">유저포인트 ↓</th><th scope="col" class="num">클리어 수</th><th scope="col">최고 난이도 기록</th><th scope="col" class="medal-column">보유 메달</th></tr></thead><tbody id="point-rows"></tbody></table></div><div class="table-foot" id="point-foot"></div><p class="ledger-footnote">게임 스탯 순위는 <button class="inline-link" data-page="stats">스탯랭킹</button>에서 확인할 수 있습니다.</p>${footer()}`;renderPointRows()}
function renderPointRows(){const all=pointUsers().filter(u=>u.name.toLowerCase().includes(toolState.boardQuery.toLowerCase()));const pages=Math.max(1,Math.ceil(all.length/20));toolState.boardPage=Math.min(pages,toolState.boardPage);const start=(toolState.boardPage-1)*20;document.querySelector('#point-rows').innerHTML=all.slice(start,start+20).map(u=>`<tr><td class="table-rank">${u.rank}</td><td class="tier-column">${trophyImage(u.rank,u.points)}</td><td><div class="point-user-cell"><button class="inline-link point-user" data-profile="${esc(u.name)}">${esc(u.name)}</button>${tierLabel(u.rank,u.points)}</div></td><td class="num score-cell">${u.points.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td class="num muted">${u.clears}</td><td><button class="inline-link" data-home-level="${u.hardest}">#${u.hardest} ${esc(levels[u.hardest-1].name)}</button></td><td class="medal-column">${compactMedals(u.name)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">일치하는 유저가 없습니다.</td></tr>';document.querySelector('#point-foot').innerHTML=`<span>${all.length?start+1:0}–${Math.min(start+20,all.length)} / ${fmt(all.length)}명</span><div class="tool-pagination"><button data-point-page="${toolState.boardPage-1}" ${toolState.boardPage===1?'disabled':''} aria-label="포인트 이전 페이지">${icon('chevronLeft')}</button><span>${toolState.boardPage} / ${pages}</span><button data-point-page="${toolState.boardPage+1}" ${toolState.boardPage===pages?'disabled':''} aria-label="포인트 다음 페이지">${icon('chevron')}</button></div>`}
function levelOptions(){return `<datalist id="tool-level-options">${levels.map(l=>`<option value="${esc(l.name)}">#${l.rank}</option>`).join('')}</datalist>`}
function findToolLevel(value){return levels.find(l=>l.name.toLowerCase()===value.trim().toLowerCase()||String(l.rank)===value.trim().replace(/^#/,''))}
function estimatePoints(score,percent,minimum,device,fps,version,cbf){const deviceBonus=device==='PC'?0:.35;const fpsBonus=!cbf&&['2.1','2.2'].includes(version)?(fps<70?.65:fps<95?.45:fps<180?.15:0):0;const progress=percent===100?1:(percent-minimum/1.3)/(100-minimum/1.3)*.666*.333;return {progress,bonus:1+deviceBonus+fpsBonus,deviceBonus,fpsBonus,total:Number((score*progress*(1+deviceBonus+fpsBonus)).toFixed(3))}}
function calculator(){const d=toolState.calculator||{level:current().name,percent:100,device:'PC',fps:240,version:'2.208',cbf:false};main.innerHTML=`${toolHeading('유저포인트 계산기','레벨과 플레이 조건을 입력하면 예상 포인트를 확인할 수 있습니다.')}<div class="tool-workbench"><form class="tool-form" id="calculator-form"><div class="form-field"><label for="calc-level">레벨 이름 또는 순위</label><input id="calc-level" list="tool-level-options" value="${esc(d.level)}" required autocomplete="off">${levelOptions()}</div><div class="form-row"><div class="form-field"><label for="calc-percent">진행률 (%)</label><input id="calc-percent" type="number" min="0" max="100" step="1" value="${d.percent}" required></div><div class="form-field"><label for="calc-version">게임 버전</label><select id="calc-version">${[['2.208','2.208 이상'],['2.2','2.207'],['2.1','2.1']].map(([v,l])=>`<option value="${v}" ${d.version===v?'selected':''}>${l}</option>`).join('')}</select></div></div><div class="form-row"><div class="form-field"><label for="calc-device">플레이 기기</label><select id="calc-device">${[['PC','PC'],['Mobile','모바일'],['iPad','iPad']].map(([v,l])=>`<option value="${v}" ${d.device===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="form-field"><label for="calc-fps">FPS</label><input id="calc-fps" type="number" min="30" max="65535" step="1" value="${d.fps}" required></div></div><label class="tool-checkbox"><input id="calc-cbf" type="checkbox" ${d.cbf?'checked':''}>CBF 사용</label><button type="submit" class="button-primary">포인트 계산</button></form><section class="tool-result" id="calculator-result" aria-label="예상 포인트" aria-live="polite"></section></div>${toolSample('레벨 점수·인정 기준은 예시입니다. 실제 포인트와 다를 수 있습니다.')}<details class="tool-explanation"><summary>계산 기준 보기</summary><p>레벨의 예시 클리어 점수에 진행률 계수와 기기·FPS 배율을 적용합니다. 이 목업의 모든 레벨은 70%부터 기록을 인정하는 예시입니다. 2.208 이상 또는 CBF 사용 시 FPS 보너스를 적용하지 않습니다.</p><p>진행률 100%는 계수 1, 부분 기록은 별도 계수를 사용합니다. <a href="https://gmdkoreaforum.com/demonlist/1" target="_blank" rel="noopener noreferrer">공식 포럼의 계산기 확인 ↗</a></p></details>${footer()}`;calculateToolPoints()}
function calculateToolPoints(){const form=document.querySelector('#calculator-form');const result=document.querySelector('#calculator-result');const d={level:form.querySelector('#calc-level').value,percent:+form.querySelector('#calc-percent').value,device:form.querySelector('#calc-device').value,fps:+form.querySelector('#calc-fps').value,version:form.querySelector('#calc-version').value,cbf:form.querySelector('#calc-cbf').checked};toolState.calculator=d;const l=findToolLevel(d.level);if(!form.checkValidity()||!l||d.percent<70){result.innerHTML=`<h2>입력을 확인해 주세요</h2><p class="tool-error">${!l?'목록에 있는 레벨 이름이나 1–940 사이 순위를 입력해 주세요.':d.percent<70?'이 레벨의 예시 인정 기준은 70% 이상입니다.':'진행률은 70–100%, FPS는 30–65,535 사이 정수로 입력해 주세요.'}</p>`;return}const r=estimatePoints(l.score,d.percent,70,d.device,d.fps,d.version,d.cbf);result.innerHTML=`<h2>예상 유저포인트</h2><div class="tool-result-value">${r.total.toLocaleString('en-US',{minimumFractionDigits:3,maximumFractionDigits:3})}<small>UP</small></div><p>#${l.rank} ${esc(l.name)} · ${d.percent}%</p><dl class="tool-breakdown"><div><dt>100% 클리어 점수</dt><dd>${l.score.toFixed(2)}</dd></div><div><dt>진행률 계수</dt><dd>× ${r.progress.toFixed(4)}</dd></div><div><dt>기기 보너스</dt><dd>+ ${r.deviceBonus.toFixed(2)}</dd></div><div><dt>FPS 보너스</dt><dd>+ ${r.fpsBonus.toFixed(2)}</dd></div><div><dt>최종 배율</dt><dd>× ${r.bonus.toFixed(2)}</dd></div></dl>`}
function demonLevelToolbar(){return `<div class="mobile-toolbar"><button id="open-sidebar">${icon('list')}레벨 목록 <b>940</b>${icon('chevron')}</button><span>이름·순위로 검색</span></div>`}
let rouletteSpin=null;
function setRouletteBusy(busy){
  document.querySelectorAll('#roulette-form input,#roulette-form button,#roulette-reset').forEach(control=>control.disabled=busy);
  const button=document.querySelector('#roulette-form button[type="submit"]');
  if(button)button.textContent=busy?'추첨 중…':'레벨 뽑기';
  document.querySelector('#roulette-result')?.setAttribute('aria-busy',String(busy));
}
function cancelRouletteSpin(){
  if(!rouletteSpin)return;
  const spin=rouletteSpin;rouletteSpin=null;spin.animation?.cancel();setRouletteBusy(false);
}
async function animateRoulette(candidates,selected){
  const result=document.querySelector('#roulette-result');
  const spin={animation:null};rouletteSpin=spin;setRouletteBusy(true);
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches){
    const reel=Array.from({length:24},(_,i)=>candidates[i%candidates.length]);
    // Shuffle the passing levels; the preselected result is the final stop.
    for(let i=reel.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[reel[i],reel[j]]=[reel[j],reel[i]]}
    reel.push(selected);
    result.innerHTML=`<h2>도전할 레벨을 뽑는 중…</h2><div class="roulette-window" aria-hidden="true"><div class="roulette-reel">${reel.map(l=>`<div class="roulette-ticket"><span>#${l.rank}</span><strong>${esc(l.name)}</strong></div>`).join('')}</div></div><p>잠시 후 결과가 표시됩니다.</p>`;
    const track=result.querySelector('.roulette-reel');
    const rowHeight=track.firstElementChild.getBoundingClientRect().height;
    spin.animation=track.animate([{transform:'translateY(0)'},{transform:`translateY(-${(reel.length-1)*rowHeight}px)`}],{duration:2400,easing:'cubic-bezier(.12,.65,.18,1)',fill:'forwards'});
    try{await spin.animation.finished}catch{return}
  }
  if(rouletteSpin!==spin||!result.isConnected)return;
  rouletteSpin=null;toolState.rouletteResult=selected;toolState.rouletteHistory.push(selected);
  setRouletteBusy(false);renderRouletteResult();
}
function roulette(){main.innerHTML=`${toolHeading('데몬리스트 룰렛','순위 범위를 정하고 다음에 도전할 레벨을 뽑아보세요.')}<div class="tool-workbench"><form id="roulette-form" class="tool-form"><div class="form-row"><div class="form-field"><label for="roulette-min">시작 순위</label><input type="number" id="roulette-min" min="1" max="940" value="1" required></div><div class="form-field"><label for="roulette-max">끝 순위</label><input type="number" id="roulette-max" min="1" max="940" value="100" required></div></div><div class="form-field"><label for="roulette-user">기록 보유 유저 <span class="muted">(선택)</span></label><input id="roulette-user" list="roulette-users" autocomplete="off" placeholder="선택한 유저의 기록 레벨 제외"><datalist id="roulette-users">${names.map(n=>`<option value="${n}">`).join('')}</datalist><small>예시 유저: ${names.slice(0,4).join(' · ')}</small></div><label class="tool-checkbox"><input id="roulette-repeat" type="checkbox" checked>이미 뽑은 레벨 제외</label><button class="button-primary" type="submit">레벨 뽑기</button><p class="tool-error" id="roulette-error" role="status"></p></form><section class="tool-result" id="roulette-result" aria-label="추첨 결과" aria-live="polite"></section></div><section class="roulette-history"><div class="record-section-heading"><h2>이번 추첨 기록</h2><button class="record-link" id="roulette-reset">초기화</button></div><ol id="roulette-history"></ol></section>${toolSample('유저별 보유 기록도 예시 데이터로 제외됩니다.')} ${footer()}`;renderRouletteResult()}
function renderRouletteResult(){const l=toolState.rouletteResult;document.querySelector('#roulette-result').innerHTML=l?`<h2>이번에 도전할 레벨</h2><div class="roulette-rank">#${l.rank}</div><h3>${esc(l.name)}</h3><p>제작 ${esc(l.creator)} · 클리어 점수 ${l.score.toFixed(2)}</p><button class="button-secondary" data-home-level="${l.rank}">레벨 상세 보기 ${icon('chevron')}</button>`:`<h2>추첨 결과</h2><div class="roulette-empty">?</div><p>조건을 정한 뒤 레벨을 뽑아주세요.</p>`;document.querySelector('#roulette-history').innerHTML=toolState.rouletteHistory.slice().reverse().map((l,i)=>`<li><span>${toolState.rouletteHistory.length-i}</span><button class="inline-link" data-home-level="${l.rank}">#${l.rank} ${esc(l.name)}</button></li>`).join('')||'<li class="muted">아직 뽑은 레벨이 없습니다.</li>'}
function drawRoulette(){if(rouletteSpin)return;const form=document.querySelector('#roulette-form');if(!form.reportValidity())return;const min=+document.querySelector('#roulette-min').value,max=+document.querySelector('#roulette-max').value,name=document.querySelector('#roulette-user').value.trim();const error=document.querySelector('#roulette-error');if(min>max){error.textContent='시작 순위는 끝 순위보다 작거나 같아야 합니다.';return}if(name&&!names.includes(name)){error.textContent='목록에 있는 예시 유저를 선택하거나 이름을 비워 주세요.';return}const userIndex=names.indexOf(name);const previous=document.querySelector('#roulette-repeat').checked?new Set(toolState.rouletteHistory.map(l=>l.rank)):new Set();const candidates=levels.filter(l=>l.rank>=min&&l.rank<=max&&!previous.has(l.rank)&&(!name||l.rank%16!==userIndex));if(!candidates.length){error.textContent='조건에 맞는 레벨이 없습니다. 범위를 넓히거나 추첨 기록을 초기화해 주세요.';return}error.textContent='';const l=candidates[Math.floor(Math.random()*candidates.length)];animateRoulette(candidates,l)}
function accountTools(){main.innerHTML=`${toolHeading('Discord 연동','Discord 로그인과 포럼 유저 연동 상태를 확인합니다.')}<div class="account-sheet"><section><span class="account-step">01</span><div><h2>Discord 로그인</h2><p>${toolState.demoAccount?'예시 계정으로 화면을 체험 중입니다. 실제 로그인 상태가 아닙니다.':'기존 Discord 계정으로 로그인할 수 있습니다.'}</p>${toolState.demoAccount?'<strong class="account-identity">ExamplePlayer <small>예시 계정</small></strong>':'<button class="button-primary" data-login>Discord로 로그인</button><button class="record-link demo-account-button" id="account-demo">예시 계정으로 살펴보기</button>'}</div></section><section><span class="account-step">02</span><div><h2>포럼 유저 연동</h2><p>로그인한 계정과 기존 기록의 주인을 연결합니다.</p>${toolState.demoAccount?toolState.linked?`<div class="account-linked"><strong>하늘 <span>연동됨 · 예시</span></strong><button class="record-link" id="account-unlink-demo">예시 연동 해제</button></div>`:'<div class="account-link-preview"><p>포럼 유저 <strong>하늘</strong> · 클리어 기록 384개</p><button class="button-secondary" id="account-link-demo">연동 화면 체험</button></div>':'<p class="muted">Discord 로그인 후 연동할 포럼 유저를 확인합니다.</p>'}</div></section></div><div class="tool-related"><button class="inline-link" data-page="nickname">닉네임 변경 요청</button><button class="inline-link" data-page="my-requests">내 최근 리퀘스트</button></div>${toolSample('로그인·연동·해제는 실제 계정에 반영되지 않습니다.')} ${footer()}`}
function nicknameTools(){main.innerHTML=`${toolHeading('닉네임 변경 요청','기존 기록을 유지하면서 포럼에 표시되는 이름 변경을 신청합니다.')}<div class="tool-workbench"><form class="tool-form" id="nickname-form"><div class="form-field"><label for="nickname-current">현재 닉네임</label><input id="nickname-current" value="하늘" readonly><small>예시 계정의 현재 닉네임입니다.</small></div><div class="form-field"><label for="nickname-new">변경할 닉네임</label><input id="nickname-new" minlength="3" maxlength="32" required autocomplete="off" placeholder="3–32자"><small>실제 신청에는 Discord 로그인이 필요합니다.</small></div><button class="button-primary" type="submit">신청 내용 미리보기</button><p class="tool-error" id="nickname-error" role="status"></p></form><section class="tool-result" id="nickname-preview" aria-live="polite"><h2>변경 내용</h2><p>새 닉네임을 입력하면 변경 전후를 확인할 수 있습니다.</p></section></div>${toolSample('이름을 입력해도 실제 변경 요청은 전송되지 않습니다.')} ${footer()}`}
function previewNickname(){const input=document.querySelector('#nickname-new');const name=input.value.trim();if(name.length<3||name.length>32||name==='하늘'){document.querySelector('#nickname-error').textContent='현재 이름과 다른 3–32자 닉네임을 입력해 주세요.';return}document.querySelector('#nickname-error').textContent='';document.querySelector('#nickname-preview').innerHTML=`<h2>닉네임 변경 미리보기</h2><div class="nickname-comparison"><span>하늘</span>${icon('chevron')}<strong>${esc(name)}</strong></div><p>기존 클리어 기록과 포인트는 유지됩니다.</p><p class="tool-preview-caption">미리보기 완료 · 실제 요청은 전송되지 않았습니다.</p><button class="record-link" data-page="my-requests">리퀘스트 화면 보기 ${icon('chevron')}</button>`}
const exampleRequests=[{id:21282,date:'2026.09.08',type:'데몬리스트 기록',name:'Kyouki · 100%',status:'대기',detail:'운영진이 영상과 인증 정보를 확인하기 전입니다.'},{id:21261,date:'2026.09.07',type:'데몬리스트 기록',name:'Acheron · 100%',status:'승인',detail:'영상 확인을 마쳤으며 순위와 포인트에 반영되었습니다.'},{id:21240,date:'2026.09.06',type:'닉네임 변경',name:'하늘 → 푸른하늘',status:'대기',detail:'닉네임 변경 신청을 검토 중입니다.'},{id:21211,date:'2026.09.05',type:'데몬리스트 기록',name:'Tidal Wave · 70%',status:'거절',detail:'원본 영상 링크에 접근할 수 없습니다. 공유 권한을 확인한 뒤 다시 신청해 주세요.'},{id:21184,date:'2026.09.04',type:'스탯랭킹 등재',name:'게임 계정 등재',status:'승인',detail:'게임 계정 인증을 확인하고 스탯랭킹에 등재했습니다.'}];
function myRequests(){main.innerHTML=`${toolHeading('내 최근 리퀘스트','제출한 신청의 처리 상태와 운영진 확인 내용을 살펴봅니다.')}<div class="tool-table-toolbar"><span>예시 내역 <strong>5건</strong></span><label class="request-status-label">상태<select id="request-status-filter" aria-label="내 리퀘스트 상태"><option value="all">전체</option><option>대기</option><option>승인</option><option>거절</option></select></label></div><div id="request-history-list" class="request-history-list"></div>${toolSample('실제 내역은 Discord 로그인 후 조회합니다.')}<button class="button-secondary" data-login>Discord로 로그인</button>${footer()}`;renderMyRequests()}
function renderMyRequests(){const filter=document.querySelector('#request-status-filter').value;document.querySelector('#request-history-list').innerHTML=exampleRequests.filter(r=>filter==='all'||filter===r.status).map(r=>`<details class="request-history-item"><summary><span class="request-number">#${r.id}</span><span class="request-description"><strong>${r.name}</strong><small>${r.type} · ${r.date}</small></span><span class="request-state state-${r.status}">${r.status}</span><span class="request-expand">${icon('chevron')}</span></summary><div class="request-resolution"><strong>${r.status==='거절'?'거절 사유':'처리 안내'}</strong><p>${r.detail}</p>${r.status==='거절'?'<button class="inline-link" data-page="requests">기록 다시 신청</button>':''}</div></details>`).join('')}
function submissionGuide(){main.innerHTML=`${toolHeading('기록 등재 필독 사항','제출 전에 자주 빠뜨리는 항목부터 확인해 주세요.')}<div class="tool-reading"><ol class="submission-checklist"><li><h2>기록 인정 기준 확인</h2><p>제출할 레벨의 최소 진행률과 영상을 먼저 확인하세요.</p><button class="inline-link" data-page="demon">레벨 정보로 이동</button></li><li><h2>클리어 영상과 원본 준비</h2><p>플레이 영상과 별도로 편집하지 않은 원본을 준비합니다. 원본의 제출 형태와 예외는 가이드라인에서 확인하세요.</p></li><li><h2>공유 권한 확인</h2><p>운영진이 제출한 영상과 파일을 열 수 있어야 합니다.</p></li><li><h2>계정과 플레이 환경 확인</h2><p>기록의 주인과 연동된 계정인지 확인하고, 사용한 기기·버전·FPS 정보를 준비하세요.</p><button class="inline-link" data-page="account">계정 연동 확인</button></li></ol><div class="tool-reading-actions"><button class="button-primary" data-page="requests">기록 등재 신청</button><button class="button-secondary" data-page="guidelines">전체 항목별 가이드</button></div>${guideSource()}</div>${footer()}`}
function guideSource(){return `<p class="tool-source">주요 내용을 요약한 목업입니다. 최신 세부 규정은 <a href="https://gmdkoreaforum.com/demonlist/1" target="_blank" rel="noopener noreferrer">공식 포럼 ↗</a>의 ‘데몬리스트 메뉴 → 기록 가이드라인’에서 확인하세요.</p>`}
function recordGuidelines(){main.innerHTML=`${toolHeading('데몬리스트 기록 가이드라인','영상, 원본 파일, 플레이 환경별 확인 사항입니다.')}<div class="tool-reading"><nav class="guide-jump" aria-label="가이드 항목"><a href="#guidelines/video">기록 영상</a><a href="#guidelines/raw">무편집 원본</a><a href="#guidelines/setup">플레이 환경</a></nav><section id="guide-video" class="guide-section"><h2>01. 기록 영상</h2><p>100% 클리어는 시작부터 완료 화면까지, 부분 기록은 도전 시작부터 사망이 확인되는 지점까지 원본에 담겨야 합니다.</p><p>제출 영상과 원본이 같은 플레이인지 확인할 수 있어야 합니다.</p></section><section id="guide-raw" class="guide-section"><h2>02. 무편집 원본</h2><p>잘라내기나 오디오 수정 없이 녹화 원본을 준비합니다. 클릭 소리가 확인되어야 하며, 파일 링크 제출을 기본으로 합니다.</p><p>생방송 영상의 인정 조건은 별도 규정을 확인하세요.</p></section><section id="guide-setup" class="guide-section"><h2>03. 플레이 환경</h2><p>버전·기기·레벨 순위에 따라 FPS 표시, 보조 프로그램 표시, 오디오 트랙 분리 등의 추가 조건이 달라집니다.</p><p>녹화 전에 자신의 플레이 환경에 해당하는 공식 규정을 확인하세요.</p></section>${guideSource()}<div class="tool-reading-actions"><button class="button-primary" data-page="requests">기록 등재 신청</button><button class="record-link" data-page="submission-guide">필독 사항 다시 보기</button></div></div>${footer()}`}
const toolRenderers={tools:toolsHome,leaderboard:pointLeaderboard,calculator,roulette,account:accountTools,nickname:nicknameTools,'my-requests':myRequests,'submission-guide':submissionGuide,guidelines:recordGuidelines};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.pointPage){toolState.boardPage=+b.dataset.pointPage;renderPointRows();return}if(b.id==='roulette-reset'){cancelRouletteSpin();toolState.rouletteHistory=[];toolState.rouletteResult=null;document.querySelector('#roulette-error').textContent='';renderRouletteResult()}if(b.id==='account-demo'){toolState.demoAccount=true;render()}if(b.id==='account-link-demo'){toolState.linked=true;render()}if(b.id==='account-unlink-demo'){toolState.linked=false;render()}});
document.addEventListener('input',e=>{if(e.target.id==='point-search'){toolState.boardQuery=e.target.value;toolState.boardPage=1;renderPointRows()}});
document.addEventListener('change',e=>{if(e.target.id==='request-status-filter')renderMyRequests()});
document.addEventListener('submit',e=>{if(e.target.id==='calculator-form'){e.preventDefault();calculateToolPoints()}if(e.target.id==='roulette-form'){e.preventDefault();drawRoulette()}if(e.target.id==='nickname-form'){e.preventDefault();previewNickname()}});

window.addEventListener('pagehide',cancelRouletteSpin);
